#:schema node_modules/wrangler/config-schema.json
name = "remix-cloudflare-workers-template"

main = "./server.ts"
workers_dev = true
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2024-01-30"

[assets]
# https://developers.cloudflare.com/workers/static-assets/binding/
binding = "ASSETS"
directory = "./build/client"

[build]
command = "pnpm run build"

[vars]
VALUE_FROM_CLOUDFLARE = "Hello from Cloudflare"
